export * from './commands/reg-cmd-query';
export * from './commands/reg-cmd-add';
export * from './commands/reg-cmd-delete';
export * from './commands/reg-cmd-import';
export * from './operations/reg-apply';
export * from './operations/reg-compare';
export * from './errors';
export * from './types';
export * from './promise-stoppable';
export * from './utils';
export * from './constants';
export * from './lookpath-sync'